name: LeonPerms
version: 1.0
main: com.leontg77.leonperms.Perms
author: LeonTG77
description: A simple permissions plugin by LeonTG77.

commands:
    perm:
        description: The main command for the plugin, see help menu.
        aliases: [perms]
